#!/usr/bin/env bash
#write a Bash script that configures a new Ubuntu machine

sudo apt-get update
sudo apt-get install ngnix
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
sudo sed -i 's/.*/Hello World!/' /var/www/html/index.nginx-debian.html
sudo service nginx start
