#!/usr/bin/env bash
#write a Bash script that configures Ubuntu machine
sudo apt-get update -y
sudo apt-get install ngnix -y
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
