#!/usr/bin/env bash
#write a Bash script that configures Ubuntu machine
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
