#!/usr/bin/env bash
#Redirection
./1-install_nginx_web_server
sed -i "s#server_name _;#server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;#" /etc/nginx/sites-enabled/default
sudo service nginx reload
