#!/usr/bin/env bash
#Redirection
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s#server_name _;#server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}#" /etc/nginx/sites-enabled/default
sudo touch /var/www/html/er404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/er404.html
sudo sed -i "s#server_name _;#server_name _;\n\n\terror_page 404 \/er404.html;#" /etc/nginx/sites-enabled/default
sudo service nginx restart
