#!/usr/bin/env bash
#Installing HAproxy
sudo apt update -y
sudo apt install haproxy -y
sudo systemctl enable haproxy
config=$(cat <<EOL
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend myfrontend
    mode http
    bind :80
    default_backend myservers

backend myservers
    balance roundrobin
    server 393408-web-01 54.237.35.210:80 check
    server 393408-web-02 34.239.107.142:80 check
EOL
)

echo "$config" | sudo tee /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
