#!/usr/bin/env bash
#Installing HAproxy
sudo apt update -y
sudo apt install haproxy -y
sudo systemctl enable haproxy
config=$(cat <<EOL
#add confi

frontend myfrontend
    mode http
    bind *:80
    default_backend myservers

backend myservers
    balance roundrobin
    server 393408-web-01 54.237.35.210:80 check
    server 393408-web-02 34.239.107.142:80 check
EOL
)

echo "$config" | sudo tee  -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
