#!/usr/bin/env bash
#This script will display "To infinity and beyond" indefinitely
echo $$ > kil7-hight.txt
trap "I am invincible!!!" SIGTERM
while true 
do
	echo "To infinity and beyond"
	sleep 2
done
