#!/usr/bin/env bash
#This bash script will print it 4th iteration "bad luck", at the 8th iteration "good luck" and for the other iterations "Best School"
i=0
while [ $i -le 9 ]
do
	if [ $i == 3 ]
	then
		echo "bad luck"
	elif [ $i == 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i+1 ))
done
