#!/usr/bin/env bash
# This script will display numbrs from 1 to 20 with some exceptions in the 4th 9th and the 17th iteration
i=1
while [ $i -le 20 ]
do
	case $i in
		4) echo "$i" && echo "bad luck from China";;
		9) echo "$i" && echo "bad luck from Japan";;
		17) echo "$i" && echo "bad luck from Italy";;
		*) echo "$i"
	esac
	i=$(( i+1))
done
