#!/usr/bin/env bash
# This script will display the time for 12 hours and 59 minutes: 
# display hours from 0 to 12
# display minutes from 1 to 59
hours=0
while [ $hours -le 12 ]
do
	min=1
	echo "Hour: $hours"
	while [ $min -le 59 ]
	do
		echo "$min"
		((min++))
	done
	((hours++))
done
