#!/usr/bin/env bash
# This bash script display the content of the current directory in a list format
for ((i=0; i<1; i++))
do
# Disable SC2012 for the following line
# shellcheck disable=SC2012
	ls | cut -d '-' -f 2
done
