#!/usr/bin/env bash
# This script will give us nformation about the school file.
target="school"
if [ -e "$target" ]
then
	echo "school file exists"
	if [ -s "$target" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$target" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
